<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="INMAAWN5384001" ignored="3" name="AQCC Parallel Test" tests="2" failures="1" timestamp="23 Jul 2019 10:25:42 GMT" time="18.043" errors="0">
  <testcase name="test2" time="0.017" classname="com.testcases.FacilityViewTests">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.001" classname="com.testcases.FacilityViewTests">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at com.testcases.FacilityViewTests.test2(FacilityViewTests.java:67)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test1" time="0.0" classname="com.testcases.FacilityViewTests">
    <ignored/>
  </testcase> <!-- test1 -->
  <testcase name="checkWhetherGlobalViewIsSelectedByDefault" time="0.0" classname="com.testcases.FacilityViewTests">
    <ignored/>
  </testcase> <!-- checkWhetherGlobalViewIsSelectedByDefault -->
  <testcase name="validateEnteringShipmentID" time="0.0" classname="com.testcases.FacilityViewTests">
    <ignored/>
  </testcase> <!-- validateEnteringShipmentID -->
</testsuite> <!-- AQCC Parallel Test -->
